### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by mclarkson** [cpuguy83/docker-volumes#18]
Is there a way to get the output in JSON? (or other structured output?)

Scratch my second question. Possibly makes no sense since this is a client to docker.
~~Does it have a remote API like docker? (so can be queried with curl + tls)~~

**Comment by mclarkson** [comment]
Thanks for that @ailispaw. That solves some problems I hadn't even thought of yet. I've compiled it and will give it a go.

**Comment by cpuguy83** [comment]
Being that docker 1.7 broke us, and docker 1.8 breaks even more things... and docker 1.9 is going to include native `docker volumes` support, I'm not going to maintain this anymore.

**Comment by mclarkson** [comment]
Thanks for the heads-up.
