### ISSUE TITLE
How to find unused volumes

### ISSUE THREAD

**Issue by anentropic** [cpuguy83/docker-volumes#21]
"Most people tend to have extra volumes laying around which are not in use because they didn't get removed with the container they were used with"

Can you please point me in the right direction for parsing the output of `docker-volumes list` to identify unused volumes (so I can remove them and free up disk space)

Or let me know if this idea doesn't make sense

**Comment by cpuguy83** [comment]
You can simply do `docker-volumes rm $(docker-volumes ls -q)`.
It will not let you remove unused volumes.

**Comment by anentropic** [comment]
```
$ docker-volumes rm $(docker-volumes ls -q)
Error pulling volumes for: f618a787041a9f362a0cfcb1ac17177e15865103104d435fc1de95fc2b8ed662
Could not find volume:  No
Could not find volume:  help
Could not find volume:  topic
Could not find volume:  for
Could not find volume:  'ls'
```

**Comment by anentropic** [comment]
OS X, boot2docker
```
$ docker --version
Docker version 1.5.0, build a8a31ef
```

**Comment by cpuguy83** [comment]
Sorry, this should be `list` not `ls`.
Please see the `docker-volumes --help`, or `docker-volumes <subcommand> --help`.

**Comment by anentropic** [comment]
ah it's obvious now you say

cheers!
