### ISSUE TITLE
Option to remove all unused volumes

### ISSUE THREAD

**Issue by mikehaertl** [cpuguy83/docker-volumes#22]
As the title says: Can we have an option to remove all volumes that are no longer used by any container? Suggestion: `docker-volumes rm -a`.

**Comment by cpuguy83** [comment]
`docker-volumes rm $(docker-volumes list -q)`
It will only ever let you remove unused volumes.

**Comment by mikehaertl** [comment]
Even better, thanks. Maybe worth adding that example to the README?
