### ISSUE TITLE
Support shortend volume IDs

### ISSUE THREAD

**Issue by mikehaertl** [cpuguy83/docker-volumes#23]
It would be great, if I could use shortened volume IDs (just as with any other docker command).

So instead of `docker-volumes rm 7cc1ed206822` I want to write `docker-volumes rm 7cc1e`

**Comment by mikehaertl** [comment]
As a workaround I've used this command now:

```sh
docker-volumes list | cut -d' ' -f3 | xargs docker-volumes rm
```

**Comment by cpuguy83** [comment]
I'm not too interested in implementing this... but if someone wants to take a stab at it, by all means.

**Comment by mikehaertl** [comment]
Well, as I'll mostly use `docker-volumes` to delete all my orphaned volumes (btw thanks for your help on [this](https://github.com/cpuguy83/docker-volumes/issues/22)) it's probably not really neccessary here.

But there's also some [ongoing discussion](https://github.com/docker/docker/pull/8484) whether to integrate this tool into docker, right? If that should happen, I think, it really should be added, because you can already shorten any other docker related Id with `docker`. This should work consistently across all docker commands.

**Comment by cpuguy83** [comment]
Closing since the the short version of the ID is supported as well as the long version.
However shortening beyond what's shown in the `list` output will not work.

**Comment by mikehaertl** [comment]
Just asking: Is this a technical limitation? I still find it pretty inconvenient to type a 12-digit hash string. If you look at git, you can throw pretty much anything at it and it will find the right ID, if it's unambiguous.
