### ISSUE TITLE
How to build it

### ISSUE THREAD

**Issue by sebelk** [cpuguy83/docker-volumes#24]
Hi,

Sorry for the question but I have no idea how to build it:
I use Fedora and did:
[root@newhope docker-volumes]# export PATH=$PATH:/usr/lib/golang/bin/linux_amd64
[root@newhope docker-volumes]# export GOPATH=$HOME/go
[root@newhope docker-volumes]# go get
go install: no install location for directory /home/docker/docker-volumes outside GOPATH

Please could you help me to build it?

Thanks in advance!

**Comment by cpuguy83** [comment]
That is just a warning. That's exactly how you build it.
See the Dockerfile for reference.

**Comment by sebelk** [comment]
thanks!
