### ISSUE TITLE
Volume path permission

### ISSUE THREAD

**Issue by sergey-dm** [cpuguy83/docker-volumes#25]
After a volume is exported, the permissions of the volume-path changed

**Comment by cpuguy83** [comment]
The volume path in the container or in the tarball?
And the file perms, or the uid/gid?

**Comment by sergey-dm** [comment]
Hi. Indeed, only the ownership of files have been changed. If you export to the archive, the files in it are already with changed ownership. I try to export postgres Data-Volume which has 999:999 ownership. After exporting to an archive, the ownership of files and directories inside of tar-archive have been changed to root:root.The same thing happens when exported directly into the container.
I hope this helps.

**Comment by cpuguy83** [comment]
Being that docker 1.7 broke us, and docker 1.8 breaks even more things... and docker 1.9 is going to include native `docker volumes` support, I'm not going to maintain this anymore.
