### ISSUE TITLE
Lack of Brew formula

### ISSUE THREAD

**Issue by richardfisk** [cpuguy83/docker-volumes#26]
Hi,

Would be interested in either creating a Brew formula for your work? As described in Brew's [Formula-Cookbook.md](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook).

Thanks,
Richard

**Comment by cpuguy83** [comment]
Thanks for the suggestion, but I'm not really interested in maintaining such a formula, especially since we are looking at getting the functionality provided by this tool directly into docker... possibly for the next release.

**Comment by richardPFisk** [comment]
Very cool, I look forward to it!
