### ISSUE TITLE
json: cannot unmarshal bool into Go value of type int

### ISSUE THREAD

**Issue by glaudiston** [cpuguy83/docker-volumes#30]
Hi, I'm trying to use the docker-volumes last release:

    docker-volumes-linux-amd64 --version
    docker-volumes version 1.1.1

But it returns a json bug:

    $ docker-volumes-linux-amd64 list
    json: cannot unmarshal bool into Go value of type int

    $ docker version
    Client version: 1.7.0-dev
    Client API version: 1.19
    Go version (client): go1.4.2
    Git commit (client): b807ac1
    OS/Arch (client): linux/amd64
    Server version: 1.7.0-dev
    Server API version: 1.19
    Go version (server): go1.4.2
    Git commit (server): b807ac1
    OS/Arch (server): linux/amd64

    $ uname -a
    Linux tonlfs 4.0.0ton_lfs_x86_64 #1 SMP Wed Apr 22 11:03:51 BRT 2015 x86_64 GNU/Linux

I'm using AUFS.

Any idea of how can a get it working ?

Thanks.

**Comment by ricardoseriani** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
I'll have to check what's going on.
Volumes were re-written in docker 1.7, maybe something broke.
Can you double-check with the actual 1.7 release instead of the dev build.

**Comment by ricardoseriani** [comment]
I'm using the actual 1.7 final release, and still doesn't work

**Comment by ysagon** [comment]
Same for me.

    Docker version 1.7.0, build 0baf609

**Comment by devinrsmith** [comment]
+1

**Comment by devinrsmith** [comment]
```
$ docker info
Containers: 8
Images: 63
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5-x86_64-linode58
Operating System: Debian GNU/Linux 7 (wheezy)
CPUs: 4
Total Memory: 3.858 GiB
Name: vesper
ID: 627D:F7VS:4P37:O7FP:LTRI:YABQ:ND2Q:676N:NAFD:UZIY:SHDQ:KKEW
WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by ricardoseriani** [comment]
@cpuguy83 Any news on this ?

**Comment by ile** [comment]
Same here.

```
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64

$ docker-volumes list
json: cannot unmarshal bool into Go value of type int

$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Using https://atlas.hashicorp.com/ubuntu/boxes/trusty64 on Vagrant/Virtualbox on Win64.

**Comment by mikehaertl** [comment]
+1

**Comment by cpuguy83** [comment]
Thanks for reporting this is now fixed. I'll post some new bins and tag a new version soon.

**Comment by mikehaertl** [comment]
@cpuguy83 Any news on the bins?
