### ISSUE TITLE
Always builds binary for Linux amd64

### ISSUE THREAD

**Issue by kushmansingh** [cpuguy83/docker-volumes#33]
After the separation of the runtime and build, the binary is always compiled for the default. The environment variables are never overwritten

**Comment by cpuguy83** [comment]
You have to set this with using the image from "Dockerfile.build", not "Dockerfile".
The "Dockerfile" image is strictly for running docker-volumes in a container.

**Comment by ncknuna** [comment]
Could you update the documentation in the README to be more clear about what should be done differently? The instructions in the README to compile an OSX version no longer work.

**Comment by cpuguy83** [comment]
I'll be happy to as soon as I get some time! :)

**Comment by cpuguy83** [comment]
This is done.

**Comment by ncknuna** [comment]
Thanks!
