### ISSUE TITLE
Error during docker run

### ISSUE THREAD

**Issue by lordigon** [cpuguy83/docker-volumes#36]
Hi,
I've tried docker-volumes on my VM CentOS 7 x64 (kernel version 3.10.0-229.1.2.el7.x86_64)
with docker version 1.5.0 I get these errors:

\# github.com/cpuguy83/docker-volumes
/usr/src/go/pkg/tool/linux_amd64/6l: /usr/src/go/pkg/linux_amd64/net.a(_cgo_import.6): cannot use dynamic imports with -d flag
/usr/src/go/pkg/tool/linux_amd64/6l: /usr/src/go/pkg/linux_amd64/runtime/cgo.a(_cgo_import.6): cannot use dynamic imports with -d flag
net(.text): __errno_location: not defined
net(.text): getaddrinfo: not defined
net(.text): free: not defined
net(.text): freeaddrinfo: not defined
net(.text): gai_strerror: not defined
net(.text): getaddrinfo: not defined
runtime/cgo(.text): stderr: not defined
runtime/cgo(.text): fwrite: not defined
runtime/cgo(.text): vfprintf: not defined
runtime/cgo(.text): fputc: not defined
runtime/cgo(.text): abort: not defined
runtime/cgo(.text): free: not defined
runtime/cgo(.text): pthread_attr_init: not defined
runtime/cgo(.text): pthread_attr_getstacksize: not defined
runtime/cgo(.text): pthread_attr_destroy: not defined
runtime/cgo(.text): sigfillset: not defined
runtime/cgo(.text): pthread_sigmask: not defined
runtime/cgo(.text): pthread_attr_init: not defined
runtime/cgo(.text): pthread_attr_getstacksize: not defined
too many errors
mv: cannot stat 'docker-volumes': No such file or directory

Any Help?

**Comment by cpuguy83** [comment]
Can you provide some context as to what you're doing here?
I don't understand what you are trying to run.

**Comment by Gordin** [comment]
I have the same problem. I just copy-pasted the instructions on how to build this…
```bash
git clone https://github.com/cpuguy83/docker-volumes.git
cd docker-volumes
docker build -t docker-volumes -f Dockerfile.build .
docker run --name docker-volumes docker-volumes
docker cp docker-volumes:/docker-volumes ./
```
It fails at the docker run step

**Comment by lordigon** [comment]
Hi cpuguy83,
I followed your instruction and get the error shown in my previous mail on docker run.

**Comment by cpuguy83** [comment]
I've built this several times with this exact method and do not see this.

**Comment by ricardoseriani** [comment]
If you run the commands like in the README.md, this will happen in the default cmd ('/go/src/github.com/cpuguy83/docker-volumes/make.sh'), but you can run pointing cmd to bash, then run or copy the file '/go/bin/docker-volumes' and it will work

**Comment by cpuguy83** [comment]
Fixed.
I'd updated to go 1.4 but apparently 1.4 changed the flags required for a static binary, which broke the compile for linux targets.
