### ISSUE TITLE
unable to use rm command

### ISSUE THREAD

**Issue by cmosetick** [cpuguy83/docker-volumes#38]
Thanks for your update to this project yesterday! I may be doing something wrong, but no matter what I feed the `rm` command, I get a `Could not find volume:` error message.

I've tried using just the guid, and also the full path. Also tried `/volumes/<guid>

Can you please let me know if I'm doing something wrong? Or alternatively, if there is something I should be looking at to fix the rm command?

I'm testing on a Mac with boot2docker at the moment.

When I `boot2docker ssh`
and then
`sudo ls -la /var/lib/docker/volumes/`
I see the unused volume I'm trying to delete

Thanks!

**Comment by cpuguy83** [comment]
You should be able to remove it by either name (I think) or ID.

**Comment by cmosetick** [comment]
Thanks Brian. I think that when you say ID, you mean the GUID. That was not working for me at all, so if you could please post an example of your workflow, that may help me out.

I'll give a volume name a try. It was not obvious to me that simply a name would work.

**Comment by ricardoseriani** [comment]
@cpuguy83 Hey Brian, any news on this ?
Even with docker-volumes 1.2 I can't remove any volumes

**Comment by cpuguy83** [comment]
I need more info.
This definitely works for me.

**Comment by ricardoseriani** [comment]
docker info
```
Containers: 2
Images: 793
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 846
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-43-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.696 GiB
Name: shadow
ID: ZIKB:GRCM:MZIA:7OMM:T4CK:GWR3:V4MC:KCRR:3V3U:ZXT7:MMHG:C2XG
WARNING: No swap limit support
```

docker-volumes --version
```
docker-volumes version 1.2
```

When I run a new container container, for example
```
docker run -d postgres:9.4
d08ac3974c8cfa19bfaf3cb019aa9018e2f2022f8ce978c480f4f6683642eae5
```

Then i show the info for the voluems
```
docker-volumes ls
       ID      |                   NAMES                   |                                           PATH                                            
+--------------+-------------------------------------------+------------------------------------------------------------------------------------------+
  90b4e2a1fad1 | focused_franklin:/var/lib/postgresql/data | /var/lib/docker/volumes/90b4e2a1fad1009c173feb9081d1cf60ef9e0c82ec9f3e978c0617fad7cb6e36  
```


If I do a docker-stop focused_franklin and a docker rm focused_franklin, the docker-volumes list:
```
        ID      |                  NAMES                   |                                           PATH                                            
+--------------+------------------------------------------+------------------------------------------------------------------------------------------+
               |                                          | /var/lib/docker/volumes/90b4e2a1fad1009c173feb9081d1cf60ef9e0c82ec9f3e978c0617fad7cb6e36  
```

Then any way I use to remove the volume fails:
```
docker-volumes rm /var/lib/docker/volumes/90b4e2a1fad1009c173feb9081d1cf60ef9e0c82ec9f3e978c0617fad7cb6e36 
Could not find volume:  /var/lib/docker/volumes/90b4e2a1fad1009c173feb9081d1cf60ef9e0c82ec9f3e978c0617fad7cb6e36
```
```
docker-volume rm 90b4e2a1fad1
Could not find volume:  90b4e2a1fad1
```

**Comment by cpuguy83** [comment]
Ok, somehow it's not getting an ID anymore if there is no container attached to it...

**Comment by cpuguy83** [comment]
Being that docker 1.7 broke us, and docker 1.8 breaks even more things... and docker 1.9 is going to include native `docker volumes` support, I'm not going to maintain this anymore.
