### ISSUE TITLE
release binary does not work on ubuntu 14.04

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [cpuguy83/docker-volumes#39]
code:
```
URL="https://github.com/cpuguy83/docker-volumes/releases/download/v1.1.1/docker-volumes-linux-amd64"
FILE="/usr/local/bin/docker-volumes"
wget $URL --output-document=$FILE
chmod +x $FILE
docker-volumes list
```

result:
```
json: cannot unmarshal bool into Go value of type int
```

**Comment by riquito** [comment]
Neither on Fedora 22

**Comment by cpuguy83** [comment]
Known issue, I just need to release new binaries.
The issue isn't related to os/distro, it's simply that docker 1.7 changed several internal bits that were being relied on here.

**Comment by cpuguy83** [comment]
Master works just fine, FYI.

**Comment by ksylvan** [comment]
For Fedora 22, neither the released binary or the build instructions work.

I was getting the "json: cannot unmarshal bool" message like above, which got me to this page, and then going through the build instructions:

    [ksylvan@ksylvan-t420 docker-volumes:(master)]$ docker build -t docker-volumes -f Dockerfile.build .
    Sending build context to Docker daemon 137.7 kB
    Sending build context to Docker daemon 
    Step 0 : FROM golang:1.4-cross
     ---> bbc500088baa
    [...]
    Step 6 : CMD /go/src/github.com/cpuguy83/docker-volumes/make.sh
     ---> Running in ad7ad9673af6
     ---> f65612d7e17d
    Removing intermediate container ad7ad9673af6
    Successfully built f65612d7e17d

And then:

    [ksylvan@ksylvan-t420 docker-volumes:(master)]$ docker run --name docker-volumes docker-volumes 
    # github.com/cpuguy83/docker-volumes
    /usr/src/go/pkg/tool/linux_amd64/6l: /usr/src/go/pkg/linux_amd64/net.a(_cgo_import.6): cannot use dynamic imports with -d flag
    /usr/src/go/pkg/tool/linux_amd64/6l: /usr/src/go/pkg/linux_amd64/runtime/cgo.a(_cgo_import.6): cannot use dynamic imports with -d flag
    net(.text): __errno_location: not defined
    net(.text): getaddrinfo: not defined
    net(.text): free: not defined
    net(.text): freeaddrinfo: not defined
    net(.text): gai_strerror: not defined
    net(.text): getaddrinfo: not defined
    runtime/cgo(.text): stderr: not defined
    runtime/cgo(.text): fwrite: not defined
    runtime/cgo(.text): vfprintf: not defined
    runtime/cgo(.text): fputc: not defined
    runtime/cgo(.text): abort: not defined
    runtime/cgo(.text): free: not defined
    runtime/cgo(.text): pthread_attr_init: not defined
    runtime/cgo(.text): pthread_attr_getstacksize: not defined
    runtime/cgo(.text): pthread_attr_destroy: not defined
    runtime/cgo(.text): sigfillset: not defined
    runtime/cgo(.text): pthread_sigmask: not defined
    runtime/cgo(.text): pthread_attr_init: not defined
    runtime/cgo(.text): pthread_attr_getstacksize: not defined
    too many errors
    mv: cannot stat 'docker-volumes': No such file or directory

**Comment by dunkeltaenzer** [comment]
you need to add ```-v /var/run/docker.sock:/var/run/docker.sock``` to the run command... Just ran into the same problem and adding the -v[...] solved it ;)

**Comment by ksylvan** [comment]
Does not work on Fedora 22.

    $ docker run -v /var/run/docker.sock:/var/run/docker.sock cpuguy83/docker-volumes list
    json: cannot unmarshal bool into Go value of type int

And the docker build command does not seem to create the needed docker-volumes binary (like I demonstrate above).

**Comment by cpuguy83** [comment]
@ksylvan Yes, the release binary does _not_ work against docker 1.7

**Comment by ksylvan** [comment]
@cpuguy83 Thanks for the response, and trying to use the "docker build" path does not seem to work, either.

**Comment by cpuguy83** [comment]
Released new binaries with docker 1.7 support.
Also fixed compile issues on linux.
Apparently they changed the flags needed for doing a static compile in go 1.4 :)

Thanks y'all.

**Comment by Andrei-Pozolotin** [comment]
works, thank you

**Comment by ksylvan** [comment]
$ docker run -v /var/run/docker.sock:/var/run/docker.sock cpuguy83/docker-volumes list
    json: cannot unmarshal bool into Go value of type int[ksylvan@ksylvan-t420 git]$ 

    $ docker pull docker.io/cpuguy83/docker-volumes
    latest: Pulling from docker.io/cpuguy83/docker-volumes
    
    f6d22f33daca: Pull complete 
    8e07d1d1f306: Pull complete 
    9f30d6ec16df: Already exists 
    902b87aaaec9: Already exists 
    9a61b6b1315e: Already exists 
    Digest: sha256:29145a766928f01aa48e3139e21c486c813e630483cf147ba3b70a90c38870ca
    Status: Downloaded newer image for docker.io/cpuguy83/docker-volumes:latest

And still getting the same:

    $ docker run -v /var/run/docker.sock:/var/run/docker.sock cpuguy83/docker-volumes list
    json: cannot unmarshal bool into Go value of type int

Built the binary, though, using the instructions (which now works) and I see this when trying to run it:

    $ sudo ./docker-volumes --docker-root /var/lib/docker list
      ID | NAMES |                PATH                  
    +----+-------+-------------------------------------+
     |       | /var/lib/docker/volumes/3ls:  
     |       | can't open '/.docker_root/':         
     |       | Permission denied

**Comment by ksylvan** [comment]
It looks like that's just an issue with some spurious output after the correct output:

    $ sudo ./docker-volumes  list
           ID      |                            NAMES                             |                                           PATH                                            
    +--------------+--------------------------------------------------------------+------------------------------------------------------------------------------------------+
      6ab063d559db | furious_hodgkin:/home/ksylvan/src/node/Ex_Files_Node_JS_EssT | /home/ksylvan/src/node/Ex_Files_Node_JS_EssT                                              
      36d6f839a92a | mongo:/data/db                                               | /var/lib/docker/volumes/36d6f839a92aee3ea65eb939caadaac7fc100e1bd2f4c2d2296ae59a94b330f2  
               |                                                              | /var/lib/docker/volumes/3ls: can't open '/.docker_root/': Permission denied
