### ISSUE TITLE
Option to truncate long lines for smaller screens?

### ISSUE THREAD

**Issue by firecat53** [cpuguy83/docker-volumes#4]
Would it be worth it for readability to add an option to trucate long lines to screen width (those /var/lib/docker/vfs/dir/xxxxx directory names are long!) ? Or just rely on something like less -S?

Scott

**Comment by cpuguy83** [comment]
Being that docker 1.7 broke us, and docker 1.8 breaks even more things... and docker 1.9 is going to include native `docker volumes` support, I'm not going to maintain this anymore.
