### ISSUE TITLE
`docker-volumes list` doesn't return all volumes on the system

### ISSUE THREAD

**Issue by hho** [cpuguy83/docker-volumes#42]
Using docker-volumes 1.2 this is what I get:

```
hho:~$ sudo ls -l /var/lib/docker/volumes
total 8
drwxr-xr-x 3 root root 4096 Jul 16 22:32 ec53b43f267d918920f4d3ec5f0bceb48bb52bd33a353ad9792f24537e10ec3b
drwxr-xr-x 3 root root 4096 Jul 16 22:32 fbddc539ece8dd6c96e5a8689b2b39ac0a8d5947be6676689d652676245de0b4
hho:~$ ./docker-volumes ls
  ID | NAMES |                                           PATH                                            
+----+-------+------------------------------------------------------------------------------------------+
     |       | /var/lib/docker/volumes/fbddc539ece8dd6c96e5a8689b2b39ac0a8d5947be6676689d652676245de0b4  
```

Besides the missing ID-Column (#38), shouldn't the output of `docker-volumes list` include both volumes?

**Comment by ksylvan** [comment]
That's probably an orphaned volume not referenced by any containers.

**Comment by hho** [comment]
Yeah, it probably is. But isn't that the entire point of `docker-volumes list` – being able to find those? The command description of `list` is "Lists _all_ volumes on the host" (emphasis mine). Also, it's used exactly like that in the workaround given in #22 by @cpuguy83 himself.

**Comment by cpuguy83** [comment]
Docker 1.7 introduced some changes that broke some stuff in docker-volumes.
I've tried to fix them but apparently there are some more.
Docker 1.8 breaks this again.

With native `docker volumes` support coming in 1.9 and the maintenance burden growing on this project, I'm going to go ahead and say I'm not maintaining this anymore.
