### ISSUE TITLE
Suggestion: A flag to point out orphaned volumes

### ISSUE THREAD

**Issue by ksylvan** [cpuguy83/docker-volumes#43]
Using this shell function (to reproduce the function of docker-volumes):

    docker_volumes () 
    { 
        docker ps -a -q | while read x; do
            docker inspect --format '{{.Name}} {{range $v, $h := .Volumes}}{{$v}} -> {{$h}} {{end}}' $x;
        done
    }

I see this set of volumes (produced by a pair of services created by docker-compose):

    $ docker_volumes 
    /figtest_db_1 /var/lib/postgresql/data -> /var/lib/docker/volumes/3831cdaad92ac8b89df1df8a3acce3f8862819aefb1862038410321b022d954d/_data 
    /figtest_data_1 /var/lib/postgresql/data -> /var/lib/docker/volumes/3831cdaad92ac8b89df1df8a3acce3f8862819aefb1862038410321b022d954d/_data 

Except I see this in /var/lib/docker/volumes

    $ sudo ls -l /var/lib/docker/volumes/
    total 8
    drwxr-xr-x. 3 root root 4096 Aug 10 13:58 3831cdaad92ac8b89df1df8a3acce3f8862819aefb1862038410321b022d954d
    drwxr-xr-x. 3 root root 4096 Aug 10 13:41 d413aa38646337462374da8861b1ff4d63246d8a4527216b20ae2cfa0fe54209

The above shows the one (shared) volume and another volume (not referenced by any containers).

Running docker-volumes, I see this:

    $ sudo $(which docker-volumes) ls
           ID      |                   NAMES                   |                                              PATH                                               
    +--------------+-------------------------------------------+------------------------------------------------------------------------------------------------+
      4accc415cb0e | figtest_db_1:/var/lib/postgresql/data,    | /var/lib/docker/volumes/3831cdaad92ac8b89df1df8a3acce3f8862819aefb1862038410321b022d954d/_data  
                   | figtest_data_1:/var/lib/postgresql/data   |                                                                                                 
                   |                                           | /var/lib/docker/volumes/d413aa38646337462374da8861b1ff4d63246d8a4527216b20ae2cfa0fe54209        

It would be great if docker-volumes could call out the orphaned volumes (or even a --orphans option that just displays the volumes that do not have any containers referring to them). This would make it trivial to clean them up.

**Comment by cpuguy83** [comment]
Cleanup is already easy since you can't remove a non-orphaned volume.
